version: '3.4'

networks: 
  trailblazer_testing:

services: 
  user_service:
    build: 
      context: .
    command: ["rails", "s"]
    environment: 
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
    depends_on: 
      - elasticsearch
      - user_service_db
      - redis
    links: 
      - user_service_db:user_service_db
      - redis:redis
      - elasticsearch:elasticsearch
    networks: 
      - trailblazer_testing
    ports: 
      - 3000:3000
